#ifndef __DEFINE_H__
#define __DEFINE_H__

// SRAM FILE VERSION
#define PSWAN_SRAM_VERSION_001	0x0001
#define PSWAN_SRAM_VERSION		PSWAN_SRAM_VERSION_001

// STATE FILE VERSION
#define PSWAN_SAVE_VERSION_001	0x0001
#define PSWAN_SAVE_VERSION		PSWAN_SAVE_VERSION_001

// CONFIG FILE VERSION
#define PSWAN_CFG_VERSION_001	"PSWAN_CFG_001"
#define PSWAN_CFG_VERSION_002	"PSWAN_CFG_002"
#define PSWAN_CFG_VERSION	PSWAN_CFG_VERSION_002

#define PSWAN_MENU_BMP		"PSWANMENU.BMP"

#define MAX_ENTRY	1024
#define MAX_PATH	512
#define MAX_NAME	256

//#define SOUND_BUF_LEN 160

#endif // __DEFINE_H__
